title: Read Serial Data with Python
hero_image: images/banner.png
description: nix-python-reading-serial-data description
version: 4
listed: false
copyedit: false
last_tested: "2020-01-27"
steps:
  - title: Introduction

